/* This file is generated by tdr. */
/* No manual modification is permitted. */

/* metalib version: 1 */
/* metalib md5sum: fe08469aaccd2d1ac639b14e9dcdfeb7 */

/* creation time: Sat Sep 23 11:22:48 2017 */
/* tdr version: 2.7.22, build at 20170613 */

#ifndef GAPSLOGSVR_metalib_h_
#define GAPSLOGSVR_metalib_h_

namespace GAPSLOGSVR
{


class MetaLib
{
        public:
                static int getVersion()
                {
                        return 1;
                }

                static const char* getName()
                {
                        return "GAPSLOGSVR";
                }

                static const char* getMd5Sum()
                {
                        return "fe08469aaccd2d1ac639b14e9dcdfeb7";
                }

                static const char* getTdrVersion()
                {
                        return "2.7.22, build at 20170613";
                }
};


}
#endif
